export const TRY_TO_LOGIN = 'TRY_TO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const UPDATE_AUTH_FORM_INPUT_STATE = 'UPDATE_AUTH_FORM_INPUT_STATE';
export const SWITCH_AUTH_VIEW = 'SWITCH_AUTH_VIEW';