export const TRY_TO_LOGOUT = 'TRY_TO_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const UPDATE_USERPAGE_FORM_INPUT_STATE = 'UPDATE_USERPAGE_FORM_INPUT_STATE';
export const TRY_TO_UPDATE_FORM_STATE = 'TRY_TO_UPDATE_FORM_STATE';
export const UPDATE_FORM_STATE_SUCCESS = 'UPDATE_FORM_STATE_SUCCESS';
export const UPDATE_FORM_STATE_FAIL = 'UPDATE_FORM_STATE_FAIL';
