export const UPDATE_CARD_FORM_NAME = 'UPDATE_CARD_FORM_NAME';
export const UPDATE_CARD_FORM_DESC = 'UPDATE_CARD_FORM_DESC';
export const CREATE_STORY_REQUEST = 'CREATE_STORY_REQUEST';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const CREATE_STORY_ERROR = 'CREATE_STORY_ERROR';
export const CREATE_STORY_RESET_STATUS = 'CREATE_STORY_RESET_STATUS';